# Gunakan image node sebagai base image
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Copy package.json dan install dependencies
COPY package*.json ./
RUN npm install

# Copy semua file ke working directory
COPY . .

# Build aplikasi
RUN npm run build

# Expose port aplikasi
EXPOSE 4173

# Command untuk menjalankan aplikasi
CMD ["npm", "run", "preview"]
