version: "3"

services:
  app:
    container_name: ci-cd-app
    image: 828705406551.dkr.ecr.ap-southeast-1.amazonaws.com/ci-cd
    ports:
      - "4173:80"
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules

volumes:
  node_modules:
