version: "3"

services:
  app:
    container_name: ci-cd-app
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/ci-cd:latest
    ports:
      - "4173:4173"
    environment:
      - NODE_ENV=production
