version: "3"

services:
  app:
    container_name: ci-cd-app
    image: 828705406551.dkr.ecr.ap-southeast-1.amazonaws.com/ci-cd
    ports:
      - "80:80"
    restart: always

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80" # Port 8080 di host, port 80 di container
    depends_on:
      - frontend
    restart: always
